/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationPendingRouteImport } from './routes/verification-pending'
import { Route as SignUpCompleteRouteImport } from './routes/sign-up-complete'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PostVerifyRouteImport } from './routes/post-verify'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VerificationPendingRoute = VerificationPendingRouteImport.update({
  id: '/verification-pending',
  path: '/verification-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpCompleteRoute = SignUpCompleteRouteImport.update({
  id: '/sign-up-complete',
  path: '/sign-up-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PostVerifyRoute = PostVerifyRouteImport.update({
  id: '/post-verify',
  path: '/post-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/post-verify': typeof PostVerifyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sign-up-complete': typeof SignUpCompleteRoute
  '/verification-pending': typeof VerificationPendingRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/post-verify': typeof PostVerifyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sign-up-complete': typeof SignUpCompleteRoute
  '/verification-pending': typeof VerificationPendingRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/post-verify': typeof PostVerifyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sign-up-complete': typeof SignUpCompleteRoute
  '/verification-pending': typeof VerificationPendingRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/$': typeof ApiPublicSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/post-verify'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/sign-up-complete'
    | '/verification-pending'
    | '/invite/$invitationId'
    | '/api/auth/$'
    | '/api/public/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/post-verify'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/sign-up-complete'
    | '/verification-pending'
    | '/invite/$invitationId'
    | '/api/auth/$'
    | '/api/public/$'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/post-verify'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/sign-up-complete'
    | '/verification-pending'
    | '/invite/$invitationId'
    | '/api/auth/$'
    | '/api/public/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PostVerifyRoute: typeof PostVerifyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SignUpCompleteRoute: typeof SignUpCompleteRoute
  VerificationPendingRoute: typeof VerificationPendingRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification-pending': {
      id: '/verification-pending'
      path: '/verification-pending'
      fullPath: '/verification-pending'
      preLoaderRoute: typeof VerificationPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up-complete': {
      id: '/sign-up-complete'
      path: '/sign-up-complete'
      fullPath: '/sign-up-complete'
      preLoaderRoute: typeof SignUpCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-verify': {
      id: '/post-verify'
      path: '/post-verify'
      fullPath: '/post-verify'
      preLoaderRoute: typeof PostVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PostVerifyRoute: PostVerifyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SignUpCompleteRoute: SignUpCompleteRoute,
  VerificationPendingRoute: VerificationPendingRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
