apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firapps-dev
resources:
  - namespace.yaml
  - database-secret.yaml
  - database.yaml
  - public-api.yaml
  - internal-api.yaml
